### ISSUE TITLE
Definitions should line-wrap

### ISSUE THREAD

**Issue by brekk** [madlib-lang/maddoc#2]
Minor issue w/r/t long-ass definitions:

![maddoc-line-wrap](https://user-images.githubusercontent.com/18919/114298087-ddbeec80-9ab4-11eb-962b-bbaaa8634bd2.gif)

**Comment by aboeglin** [comment]
Ah I haven't seen that one. It's now the case!

**Comment by aboeglin** [comment]
Well, it's not in master yet but it'll happen soon. I'll link the PR.
